CLASS zbp_r_cs08_customers000 DEFINITION
  PUBLIC
  ABSTRACT
  FINAL
  FOR BEHAVIOR OF zr_cs08_customers000 .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zbp_r_cs08_customers000 IMPLEMENTATION.
ENDCLASS.
